name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run preprocessing
        run: python preprocessing.py

      - name: Train model
        run: python train_model.py

      - name: Commit trained model
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add model.pkl
        
          

          git commit -m "Update model.pkl" || echo "No changes to commit"
       
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Chidinmaidonor/housing-price-ci-cd-pipeline.git HEAD:main
          

      - name: Deployment info
        run: |
          echo "Code pushed to main branch. Streamlit Cloud will
                now pull latest version and redeploy automatically."
